<?php require_once 'header.phtml'; ?>

<ul class="list-group">
    <?php foreach ($courses as $course): ?>
        <li class="list-group-item item-course">
            <div class="label">
                <b>Nombre: <?= htmlspecialchars($course->nombre) ?></b><br>
                Descripción: <?= htmlspecialchars($course->descripcion) ?>
            </div>
            <div class="actions">
                <a href="editar/<?= $course->id ?>" type="button" class='btn btn-primary btn-sm ml-auto'>Editar</a>
                <a href="eliminar/<?= $course->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            </div>
        </li>
    <?php endforeach; ?>
</ul>

<?php require_once 'footer.phtml'; ?>
