<?php require_once 'header.phtml'; ?>

<ul class="list-group">
    <?php foreach($courses as $course): ?>
        <li class="list-group-item item-student">
            <div class="label">
                <b>Categoría: </b> <?= $course->categoria ?> <br> 
                <b>Nombre: </b> <?= $course->nombre ?> <br> 
                <b>Descripción: </b> <?= $course->descripcion ?> <br> 
            </div>
            
        </li>
    <?php endforeach ?>
</ul>

<?php require_once 'footer.phtml'; ?>
