<?php require_once 'header.phtml'; ?>

<ul class="list-group">
    <?php foreach($courses as $course): ?>
        <li class="list-group-item item-student">
            <div class="label">
                <b>Nombre: </b> <?= $course->nombre ?> <br> 
                <b>Descripción: </b><?= $course->descripcion ?> <br> 
                <b>Duración: </b><?= $course->duracion ?> <br> 
                <b>Profesor/a: </b><?= $course->profesor ?> <br> 
                <b>Costo: </b><?= $course->costo ?>
            </div>
            <div class="actions">
                <a href="editar/<?= $course->ID_curso ?>" type="button" class='btn btn-primary btn-sm ml-auto'>Editar</a> 
                <a href="eliminar/<?= $course->ID_curso ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<?php require_once 'footer.phtml'; ?>
