</main>

<footer class="footer d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
    <div class="text-center"> <!-- Cambiado a text-center para centrar el contenido -->
        <h4 class="mb-1">Para más información...</h4> <!-- Usar mb-1 para reducir el margen -->
        <p class="mb-0"><b>Dirección:</b> Itala 555, Buenos Aires. <b>- Celular:</b> 2494263578</p> <!-- Eliminar márgenes -->
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>
