<?php require_once 'header.phtml'; ?>

<div class="container mt-4">
    <h2>Agregar Nuevo Curso</h2>
    <form action="addNewCourse" method="POST">
    <div class="mb-3">
        <label for="categoria" class="form-label">Categoría:</label>
        <select class="form-control" id="categoria" name="categoria" required>
            <option value="Uñas">Uñas</option>
            <option value="Peluquería">Peluquería</option>
            <option value="Maquillaje">Maquillaje</option>
            <option value="Cuidados">Cuidados</option>
        </select>
    </div>


        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre:</label>
            <input type="text" class="form-control" id="nombre" name="nombre" required>
        </div>

        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción:</label>
            <textarea class="form-control" id="descripcion" name="descripcion" rows="3" required></textarea>
        </div>

        <div class="mb-3">
            <label for="duracion" class="form-label">Duración:</label>
            <input type="text" class="form-control" id="duracion" name="duracion" required>
        </div>

        <div class="mb-3">
            <label for="profesor" class="form-label">Profesor/a:</label>
            <input type="text" class="form-control" id="profesor" name="profesor" required>
        </div>

        <div class="mb-3">
            <label for="costo" class="form-label">Costo:</label>
            <input type="number" class="form-control" id="costo" name="costo" step="0.01" required>
        </div>

        <div class="mb-3">
            <label for="url_imagen" class="form-label">URL de la Imagen:</label>
            <input type="url" class="form-control" id="url_imagen" name="url_imagen" >
        </div>

        <button type="submit" class="btn btn-primary" href="listarCursos"  >Agregar Curso</button>
        <a href="home" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

<?php require_once 'footer.phtml'; ?>
