<?php require 'templates/header.phtml' ?>

<div class="container mt-5 d-flex justify-content-center"> <!-- Centro el formulario -->
    <form method='post' action='login' class="w-50"> <!-- Ancho del formulario ajustado -->
        <?php if ($error): ?>
            <div class='alert alert-danger' role='alert'>
                <?= htmlspecialchars($error) ?> <!-- Escapando el error -->
            </div>
        <?php endif ?>

        <div class='form-group'>
            <label for='email'>Usuario</label>
            <input type='text' class='form-control' id='email' name='email' required>
        </div>
        <div class='form-group'>
            <label for='password'>Password</label>
            <input type='password' class='form-control' id='password' name='password' required>
        </div>
        
        <button type='submit' class='btn btn-primary mt-4'>Login</button> <!-- Añadido margen superior al botón -->
    </form>
</div>

<?php require 'templates/footer.phtml' ?>
