<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL; ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Glow & Go</title>
</head>

<body>
    
    <header class="header">
        <h1 class="navbar-brand">Glow & Go</h1> 
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
            </div>
        </nav>
        <p>Bienvenido a nuestra academia de belleza! Ofrecemos una variedad de cursos diseñados para todos los niveles, 
            desde principiantes hasta expertos. Únete a nosotros y descubre las técnicas más innovadoras para resaltar la
             belleza única de cada persona. ¡Empieza tu viaje hacia la excelencia en belleza hoy mismo!.</p>
        <a class="btn btn-pink btn-login" href="login">Iniciar sesión</a> 
    </header>

    <main class="container mt-3">
        
    </main>

</body>
</html>
