<?php require_once 'templates/headerHome.phtml'; ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
<main class="container mt-3">
    <div class="row text-center">
        <div class="col-md-3 mb-4">
            <div class="card bg-pink">
                <div class="card-body">
                    <h5 class="card-title"> Curso de maquillaje</h5>
                    <p class="card-text">Únete a nuestro curso de maquillaje y aprende de expertos las técnicas más 
                        innovadoras para realzar tu belleza. Desde looks deslumbrantes para ocasiones especiales hasta
                         consejos prácticos para el día a día, este curso te dará las herramientas para convertirte en 
                         tu propia artista del maquillaje. ¡Potencia tu creatividad y confianza mientras te diviertes!</p>
                </div>
            </div>
        </div>
        <div class="col-md-3 mb-4">
            <div class="card bg-pink">
                <div class="card-body">
                    <h5 class="card-title">Curso de uñas</h5>
                    <p class="card-text">Descubre el fascinante mundo del diseño de uñas en nuestro curso especializado. 
                        Aprende técnicas de manicura, decoración y tendencias actuales que te permitirán crear estilos únicos 
                        y deslumbrantes. Ya seas principiante o experta, este curso te equipará con las habilidades para
                         destacar y dejar una huella en el mundo de la belleza. ¡Luce tus creaciones y potencia tu pasión!</p>
                </div>
            </div>
        </div>
        <div class="col-md-3 mb-4">
            <div class="card bg-pink">
                <div class="card-body">
                    <h5 class="card-title">Curso de peluqueria</h5>
                    <p class="card-text">Adéntrate en el emocionante arte de la peluquería con nuestro curso práctico y dinámico.
                         Aprende desde cortes y peinados hasta técnicas de coloración y tratamiento del cabello. Nuestros expertos te 
                         guiarán en cada paso, brindándote las herramientas necesarias para convertirte en una profesional del estilismo.
                          ¡Transforma tu pasión por el cabello en una carrera exitosa!</p>
                </div>
            </div>
        </div>
        <div class="col-md-3 mb-4">
            <div class="card bg-pink">
                <div class="card-body">
                    <h5 class="card-title">Curso de cuidados</h5>
                    <p class="card-text">Descubre el secreto de una piel radiante con nuestro curso de cuidados del 
                        cuerpo y limpiezas faciales. Aprende sobre tratamientos efectivos, técnicas de masaje y rutinas 
                        personalizadas que elevarán tu bienestar y belleza. Ideal para quienes desean mejorar su cuidado 
                        personal o iniciar una carrera en el área de la estética. ¡Regálate a ti misma la experiencia de 
                        cuidarte y brillar!</p>
                </div>
            </div>
        </div>
    </div>
</main>
</body>
</html>

<?php require_once 'templates/footer.phtml'; ?>