<?php require_once 'header.phtml'; ?>

<ul class="list-group">
    <li class="list-group-item item-student">
        <div class="label">
            <b>Nombre: </b> <?= $student->nombre ?> <br> 
            <b>Apellido: </b><?= $student->apellido ?> <br> 
            <b>DNI: </b><?= $student->dni ?> <br> 
            <b>Celular: </b><?= $student->celular ?> <br> 
            <b>Domicilio: </b><?= $student->domicilio ?>
        </div>
    </li>
</ul>

<?php require_once 'footer.phtml'; ?>
