<?php require_once 'header.phtml'; ?>

<ul class="list-group">
    <li class="list-group-item item-student">
        <div class="label">
            <b>Categoría: </b> <?= $course->categoria ?> <br>
            <b>Nombre: </b> <?= $course->nombre ?> <br>  
            <b>Descripción: </b><?= $course->descripcion ?> <br> 
            <b>Duración: </b><?= $course->duracion ?> <br> 
            <b>Profesor/a: </b><?= $course->profesor ?> <br> 
            <b>Costo: </b><?= $course->costo ?><br>
            <?= $course->imagen ?>
        </div>
    </li>
</ul>

<?php require_once 'footer.phtml'; ?>
