<?php require_once 'header.phtml'; ?>

<ul class="list-group">
    <?php foreach($students as $student): ?>
        <li class="list-group-item item-student">
            <div class="label">
                <b>Nombre: </b><?= $student->nombre ?> <br> 
                <b>Apellido: </b><?= $student->apellido ?> <br> 
                <b>DNI: </b><?= $student->dni ?> <br>
                <b>Celular: </b><?= $student->celular ?> <br> 
                <b>Domicilio: </b><?= $student->domicilio ?>
            </div>
            <div class="actions">
                <a href="editar/<?= $student->ID_alumno ?>" type="button" class='btn btn-primary btn-sm ml-auto'>Editar</a> 
                <a href="eliminar/<?= $student->ID_alumno ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            </div>
        </li>
    <?php endforeach ?>
</ul>


<?php require_once 'footer.phtml';?>