<?php require_once 'header.phtml'; ?>

<?php if (isset($_SESSION['ROLE']) && $_SESSION['ROLE'] === 'admin'): ?>
    <div class="d-flex justify-content-end mb-3">
        <a href="formNuevoAlumno" type="button" class='btn btn-success'>Agregar Nuevo</a>
    </div>
<?php endif; ?>

<ul class="list-group">
    <?php foreach($students as $student): ?>
        <li class="list-group-item item-student mb-4 border-top"> 
            <div class="d-flex align-items-start">
                <div class="label flex-grow-1">
                    <b>Nombre: </b> <?= htmlspecialchars($student->nombre) ?> <br> 
                    <b>Apellido: </b> <?= htmlspecialchars($student->apellido) ?> <br> 
                    <b>DNI: </b> <?= htmlspecialchars($student->dni) ?> <br>
                    <b>Celular: </b> <?= htmlspecialchars($student->celular) ?> <br> 
                    <b>Domicilio: </b> <?= htmlspecialchars($student->domicilio) ?>
                </div>
            </div>
            <?php if (isset($_SESSION['ROLE']) && $_SESSION['ROLE'] === 'admin'): ?>
                <div class="actions mt-3">
                    <a href="formEditarAlumno/<?= $student->ID_alumno ?>" type="button" class='btn btn-pink btn-sm ml-auto'>Editar</a> 
                    <a href="eliminarAlumno/<?= $student->ID_alumno ?>" type="button" class='btn btn-pink btn-sm ml-auto'>Borrar</a>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>

<?php require_once 'footer.phtml'; ?>
