<?php require_once 'header.phtml'; ?>

<?php if (isset($_SESSION['ROLE']) && $_SESSION['ROLE'] === 'admin'): ?>
    <div class="d-flex justify-content-end mb-3">
        <a href="formNuevoAlumno" type="button" class='btn btn-success'>Agregar Nuevo</a>
    </div>
<?php endif; ?>


<ul class="list-group">
    <?php foreach($students as $student): ?>
        <li class="list-group-item item-student">
            <div class="label">
                <b>Nombre: </b><?= $student->nombre ?> <br> 
                <b>Apellido: </b><?= $student->apellido ?> <br> 
                <b>DNI: </b><?= $student->dni ?> <br>
                <b>Celular: </b><?= $student->celular ?> <br> 
                <b>Domicilio: </b><?= $student->domicilio ?>
            </div>
            <?php if (isset($_SESSION['ROLE']) && $_SESSION['ROLE'] === 'admin'): ?>
                <div class="actions">
                    <a href="formEditarAlumno/<?= $student->ID_alumno ?>" type="button" class='btn btn-primary btn-sm ml-auto'>Editar</a> 
                    <a href="eliminarAlumno/<?= $student->ID_alumno ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>

<?php require_once 'footer.phtml'; ?>
