<?php require_once 'header.phtml'; ?>
<h2>Curso: <?= $students[0]->curso_nombre ?></h2>
<ul class="list-group">

    <?php foreach($students as $student): ?>
        <li class="list-group-item item-student">
            <div class="label">
                <b>Nombre: </b><?= $student->alumno_nombre ?> <br> 
                <b>Apellido: </b><?= $student->apellido ?> <br> 
            </div>
        </li>
    <?php endforeach ?>
</ul>

<?php require_once 'footer.phtml'; ?>
